#!/bin/bash
set -e

cat .io.livecode.ch/header.txt $1 .io.livecode.ch/footer.txt >out.rb

echo '-----> [$1, $2, $3]'
ruby -e "p ['$1', '$2', '$3']"

echo '-----> out.rb'
ruby -e "p File.read('out.rb')"

